### PR TITLE
Project: Milestone 2

### PR DESCRIPTION
**Pull request by imhilla**
Kindly review codes for Milestone 2 of the TicTacToe ruby project. 
-The suggested branch name was user_interface. 
-The file is responsible for user interaction.
-Here are the steps we followed:
-Prompted the players using puts
-Collected user input using get.chomp.
-Mocked the basic flow of the game

Regards.
Hillary & Taiwo

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Hillary Odhiambo**, I'm Sarah, your reviewer for this PR 👩‍🚀  
(Only Hillary name appeared in this code review request, make sure you are not checking 'I worked alone' by accident in the next requests)

Good job starting planing your game!

There's still some requirements missing though, check the comments below 🦾 

--------

## Changes Required 🏗️ 🐛 💡

- [ ] [OPTIONAL] game asks players for their names

- [ ] Show the board to the users before the first turn.

- [ ] [OPTIONAL] You could have different messages for numbers out of the range and numbers from cells that are already filled with an 'O' or 'X'.

- [ ] How are you planning to change the game_won variable? Mock a method or simple conditional checking if one of the users won and if so change the game_won variable then.

- [ ] [OPTIONAL FOR THIS MILESTONE] Instead of repeating yourselves with the player 1 and then player 2 think about a smarter way to alternate between the players and repeting less code.

-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
The project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team, 
### You did a great job so far :+1: 
Still, you have not implemented all changes required previously:
* [x] The board is not displaying and when I try to run your project an error appears:
`undefined method render` That should be fixed.
* [x] `game_won` variable is not changing anywhere. As @uryelah asked earlier add a method that will show how `game_won` should change. It can be not working yet, but you need to have everything prepared for the next milestone.  

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by taiwocoker** [comment]
> ## Hi Team,
> ### You did a great job so far 👍
> Still, you have not implemented all changes required previously:
> 
> * [x]  The board is not displaying and when I try to run your project an error appears:
>   `undefined method render` That should be fixed.
> * [x]  `game_won` variable is not changing anywhere. As @uryelah asked earlier add a method that will show how `game_won` should change. It can be not working yet, but you need to have everything prepared for the next milestone.
> 
> ### Please kindly fix the above issues and send another code review request.
> If you have any questions or need help, you can message me on slack (@ Olga Pelts). _Happy coding_
We initiated game_won first with false, it became true on line 24.

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required 🔍 

Hi Team! 👋 
Thanks for addressing previous reviews!
However, you forgot to address the `game_won` issue mentioned by @pelzolga123 

What she explained is that you have no condition (whether in a comment or otherwise) where you change the status of `game_won` based on if user had a winning position.

Also you are missing output if game is a draw. so something like 
```ruby
if !game_won
  puts "game is a draw"
```
should suffice.

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by MarioDena — APPROVED** [review]
Good work implementing the requested changes. 👍 

Good luck on your journey! 🥇 

## Milestone approved

**Pull request merged**
