### PR TITLE
Project: Milestone 3(Game logic)

### PR DESCRIPTION
**Pull request by taiwocoker**
In this milestone, we added:
- The Board Class which has all the methods involved with the board
-The Validate Class which validates the player's position and input
-The main file that houses all the classes and initiates our TicTacToe game
Kindly review our pull request and give good feedback. 
Thanks.
Hillary & Taiwo.
Regards.

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

You've really done quite well on this @taiwocoker  and @imhilla 👏

However, let's make the following corrections to make your project look even more awesome:

- [ ] It would be more user friendly if you used numbers for each board position in place of dashes as the users can easily pick the numbers and not have to guess which number belongs to a board position.[Screenshot]
ice_screenshot_20200525-130124

- [ ] Kindly remove the puts statements in your `lib/board.rb` file as all puts statements should be in the `main.rb` file.

- [ ] Optional - Consider displaying the board even after the player has won to show the winning position.

**Once more this looks good. 🚀**


Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Almost there! 🏃 

Hi Team!

We got what your previous reviewer requested, however, I see one bug in your code.

Your UI does not successfully terminate on draw or display that draw occurred.
See the below screenshot and kindly address. 🙏 
Screen Shot 2020-05-25 at 3 55 35 PM

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by lekegitrepo** [comment]
#### Hi @taiwocoker and @imhilla :100: :1st_place_medal: 
#### Good job. This project is approved :+1: 

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved

**Pull request merged**
